name: flutter_browser
description: Create and run a sandboxed browser in all platform and not just a webview
version: 0.0.1
homepage: https://github.com/Loschia/flutter_browser

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
#TODO: force wasm build for the web build when available here
#  web:
#    compiler:
#      release:
#        module: wasm
#      debug:
#        module: wasm